/*
 * This pretends (badly) to be a TypeAlias type node, which would normally be
 * generated by flow-parser from the following code:
 *
 * type aType = {};
 *
 */
import * as espree from "espree";

var program = espree.parse("var x = 's'");
program.body[0].type = 'TypeAlias';

export default program;
