name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Install Packages
      run: npm install
    - name: Lint
      run: npm run lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 18]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test:ci
  test-with-node8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 8
      uses: actions/setup-node@v2
      with:
        node-version: 8
    - name: Install Packages
      run: |+
        npm install
        npm install --no-save "eslint@5"
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test:ci
